### ISSUE TITLE
Exception parsing favourites

### ISSUE THREAD

**Issue by emrul** [archivy/archivy-hn#4]
Hi, just trying this out for the first time and it got to page 3 of my favourites and then threw an exception:
```
Traceback (most recent call last):
  File "/usr/local/bin/archivy", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/archivy_hn/__init__.py", line 105, in hn_sync
    post_id = int(tree_subtext_each[num_subtext - 1]['href'].split("=")[1])
ValueError: invalid literal for int() with base 10: '25400809&un'
```

**Comment by Uzay-G** [comment]
Sorry for taking time to answer this, I just fixed the bug and published a new release. You can just update the package and it'll work :)
